name: beyond-semantics
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.6=py310hf71b8c6_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.28.0=pyh707e725_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.21.3=h143b758_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgomp=14.1.0=h77fa898_1
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py310h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.0.0=py310ha75aee5_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.10.15=he870216_1
  - python_abi=3.10=2_cp310
  - pyzmq=26.2.0=py310h71f11fc_2
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py310ha75aee5_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=ha4adb4c_5
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==0.21.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - altair==5.4.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.0
      - async-timeout==5.0.1
      - attrs==24.2.0
      - bitsandbytes==0.44.1
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.2.0
      - deepspeed==0.12.6
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - einops-exts==0.0.4
      - fastapi==0.115.0
      - ffmpy==0.4.0
      - filelock==3.16.1
      - flash-attn==2.6.3
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gradio==4.16.0
      - gradio-client==0.8.1
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==0.17.3
      - httpx==0.24.0
      - huggingface-hub==0.25.1
      - hydra-core==1.3.2
      - idna==3.10
      - importlib-resources==6.4.5
      - jinja2==3.1.4
      - jiter==0.7.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - latex2mathml==3.77.0
      - llvmlite==0.43.0
      - markdown-it-py==3.0.0
      - markdown2==2.5.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - narwhals==1.9.1
      - networkx==3.3
      - ninja==1.11.1.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - openai==1.54.1
      - opencv-python==4.11.0.86
      - orjson==3.10.7
      - pandas==2.2.3
      - peft==0.13.0
      - pillow==10.4.0
      - propcache==0.2.1
      - protobuf==5.28.2
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.0
      - pycocotools==2.0.8
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pynndescent==0.5.13
      - pynvml==11.5.3
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.12
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.3
      - rich==13.9.2
      - rpds-py==0.20.0
      - ruff==0.6.9
      - safetensors==0.4.5
      - scikit-learn==1.2.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==2.15.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - smmap==5.0.1
      - sniffio==1.3.1
      - starlette==0.38.6
      - svgwrite==1.4.3
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - timm==0.6.13
      - tokenizers==0.15.1
      - tomlkit==0.12.0
      - torch==2.1.2
      - torchvision==0.16.2
      - tqdm==4.66.5
      - transformers==4.37.2
      - triton==2.1.0
      - typer==0.12.5
      - tzdata==2024.2
      - umap-learn==0.5.6
      - urllib3==2.2.3
      - uvicorn==0.31.0
      - wandb==0.18.3
      - wavedrom==2.0.3.post3
      - websockets==11.0.3
      - xxhash==3.5.0
      - yarl==1.18.3